### ISSUE TITLE
genomePlotIntermediate.R shape with no category

### ISSUE THREAD

**Issue by harrig12** [hyginn/BCBBH-2018#3]
When I get to the for loop on line 475 there is a shape (myshapes[[672]]) that has a NULL value for category.

**Comment by hyginn** [comment]
Can't reproduce. myShapes has length 671 coming into the loop and the loop accesses it only via the loop variable, which is set to 1:length(myShapes). Fixed an unrelated bug, but the code works for me from start to end.
